---
default_stages:
  - commit
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        files: \.(conf|j2|js|json|rb|md|py|sh|tf|tm?pl|txt|yaml|yml)$
      - id: check-case-conflict
      - id: check-json
      - id: check-toml
      - id: end-of-file-fixer
  - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: '2.7.2'
    hooks:
      - id: editorconfig-checker-system
        alias: ec
  - repo: https://github.com/python-poetry/poetry
    rev: '1.7.1'
    hooks:
    -   id: poetry-check
    -   id: poetry-lock
    -   id: poetry-export
    -   id: poetry-install
